<a href="https://colab.research.google.com/github/Krish7grg/Cn6005-PortfolioAI/blob/main/Week_10_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# 1. Download NLTK stopwords (if not already downloaded)
# Note: In Google Colab, this usually runs without issue.
nltk.download('stopwords', quiet=True)

# --- Data Loading and Preparation using the provided CSV ---

# Load the CSV file
df = pd.read_csv("sentiment_analysis.csv")

# 2. Split the data into features (X: text) and labels (y: sentiment)
X = df['text']
y = df['sentiment']

print(f"Total data samples loaded: {len(X)}")
print(f"Sentiment labels found: {np.unique(y)}")
print("-" * 30)


# 3. Split the data into training and testing sets (80% train, 20% test)
# stratify=y ensures the training and test sets have the same proportion of each sentiment label.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")
print("-" * 30)

# 4. Vectorize the text data using CountVectorizer
vectorizer = CountVectorizer(stop_words='english')
X_train_counts = vectorizer.fit_transform(X_train)
X_test_counts = vectorizer.transform(X_test)

print(f"Training data matrix shape: {X_train_counts.shape}")
print("-" * 30)

# 5. Train a Naive Bayes classifier
classifier = MultinomialNB()
classifier.fit(X_train_counts, y_train)

# 6. Make predictions on the test set
predictions = classifier.predict(X_test_counts)

# 7. Evaluate the model
labels = np.unique(y)
accuracy = accuracy_score(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions, labels=labels)
class_report = classification_report(y_test, predictions)

# 8. Print results
print("### Model Evaluation Results (Using 'sentiment_analysis.csv') ###")
print(f"Accuracy: {accuracy:.2f}")

print("\nConfusion Matrix:")
print("Labels (rows/cols):", labels)
print(conf_matrix)

print("\nClassification Report:")
print(class_report)

Total data samples loaded: 499
Sentiment labels found: ['negative' 'neutral' 'positive']
------------------------------
Training samples: 399
Testing samples: 100
------------------------------
Training data matrix shape: (399, 1072)
------------------------------
### Model Evaluation Results (Using 'sentiment_analysis.csv') ###
Accuracy: 0.63

Confusion Matrix:
Labels (rows/cols): ['negative' 'neutral' 'positive']
[[ 9 11  7]
 [ 2 30  8]
 [ 1  8 24]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.75      0.33      0.46        27
     neutral       0.61      0.75      0.67        40
    positive       0.62      0.73      0.67        33

    accuracy                           0.63       100
   macro avg       0.66      0.60      0.60       100
weighted avg       0.65      0.63      0.61       100

